### ISSUE TITLE
Rename vendor folder to .vendor to prevent breaking Drupal/Drush

### ISSUE THREAD

**Issue by fidelix** [Snugug/generator-aurora#4]
Drupal looks for for .info files in all folders, and it thinks /vendor/ruby/2.0.0/gems/ffi-1.9.3/ext/ffi_c/libffi/doc/ is a theme folder because it has a .info file inside of it. This crashes a lot of standard Drupal operations and breaks drush completely.

Renaming the folder from vendor to .vendor and updating .bundle/config to reflect that worked fine for me.

**Comment by fidelix** [comment]
Unfortunately the same thing happened with a package inside node_modules folder, and it can't be renamed like the vendor dir.
node_modules/gulp-iconfont/node_modules/gulp-svgicons2svgfont/node_modules/svgicons2svgfont/coverage

Any ideas on how to prevent other users from running into this problem other than documenting the issue?

**Comment by Snugug** [comment]
I think the thing to do here is document the issues and push for changes upstream in Drupal. `vendor` can be renamed to `.vendor` easily (and `bower_components` too, but that's a slightly harder issue), but `node_modules` straight up can't and Drupal should be OK with not failing totally if it doesn't recognize something.

**Comment by startinggravity** [comment]
I'm running into the problem described here. When I run `yo aurora` to create a subtheme I get several .info files in /vendor/bundle/ruby/2.0.0/build_info/.

To attempt to fix I ran `npm update -g generator-aurora` and then ran `yo` to find that the Aurora generator version is 0.2.3. 

According to https://drupal.org/node/2283045 the problem is fixed in the generator. It would seem I'm not getting the update or it is not fixed.

**Comment by startinggravity** [comment]
More information: When I run `npm view -g generator-aurora version` I am told I have version 0.2.4.

I'm not sure why there is a discrepancy.

**Comment by iamcarrico** [comment]
Fixed, pushing to npm this morning.

**Comment by iamcarrico** [comment]
I am not sure about your discrepancy @startinggravity --- but I am about to push a new tag and release to npm.

**Comment by startinggravity** [comment]
Thanks, @iamcarrico. I will try again shortly to see if the new push did the trick.

**Comment by startinggravity** [comment]
I'm still not entirely clear what caused my problem. I apparently had two versions of yo and the generator. All I know is I had to blow up Node and start over. Once I did that I was able to get the correct generator version to work.

**Comment by minneapolisdan** [comment]
Thanks for this post, I was going crazy trying to figure out this error. I couldn't clear cache, drush or no drush.
